-- Forum backend — MySQL schema
-- Run with: mysql -u root -p < db/schema.sql
-- All identifiers use CHAR(36) UUIDs generated by the application.

CREATE DATABASE IF NOT EXISTS forum
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE forum;

-- Drop in dependency order so the script is re-runnable.
DROP TABLE IF EXISTS friendships;
DROP TABLE IF EXISTS message_votes;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS topic_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS topics;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id                  CHAR(36)      NOT NULL,
  username            VARCHAR(50)   NOT NULL,
  username_normalized VARCHAR(50)   NOT NULL,
  email               VARCHAR(255)  NOT NULL,
  email_normalized    VARCHAR(255)  NOT NULL,
  password_hash       CHAR(128)     NOT NULL,   -- SHA-512 hex digest
  password_salt       CHAR(32)      NOT NULL,   -- 16 random bytes, hex
  role                ENUM('USER','ADMIN') NOT NULL DEFAULT 'USER',
  bio                 VARCHAR(500)  NULL,
  avatar_url          VARCHAR(255)  NULL,
  banned              TINYINT(1)    NOT NULL DEFAULT 0,
  last_login_at       DATETIME      NULL,
  created_at          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_username (username_normalized),
  UNIQUE KEY uq_users_email (email_normalized)
) ENGINE=InnoDB;

CREATE TABLE topics (
  id          CHAR(36)     NOT NULL,
  title       VARCHAR(180) NOT NULL,
  body        TEXT         NOT NULL,
  author_id   CHAR(36)     NOT NULL,
  state       ENUM('open','closed','archived') NOT NULL DEFAULT 'open',
  visibility  ENUM('public','private')         NOT NULL DEFAULT 'public',
  created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_topics_author (author_id),
  KEY idx_topics_created (created_at),
  CONSTRAINT fk_topics_author FOREIGN KEY (author_id)
    REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE tags (
  id   CHAR(36)    NOT NULL,
  name VARCHAR(40) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_tags_name (name)
) ENGINE=InnoDB;

CREATE TABLE topic_tags (
  topic_id CHAR(36) NOT NULL,
  tag_id   CHAR(36) NOT NULL,
  PRIMARY KEY (topic_id, tag_id),
  KEY idx_topic_tags_tag (tag_id),
  CONSTRAINT fk_topic_tags_topic FOREIGN KEY (topic_id)
    REFERENCES topics (id) ON DELETE CASCADE,
  CONSTRAINT fk_topic_tags_tag FOREIGN KEY (tag_id)
    REFERENCES tags (id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE messages (
  id         CHAR(36) NOT NULL,
  topic_id   CHAR(36) NOT NULL,
  author_id  CHAR(36) NOT NULL,
  body       TEXT     NOT NULL,
  image_url  VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_messages_topic (topic_id),
  KEY idx_messages_author (author_id),
  CONSTRAINT fk_messages_topic FOREIGN KEY (topic_id)
    REFERENCES topics (id) ON DELETE CASCADE,
  CONSTRAINT fk_messages_author FOREIGN KEY (author_id)
    REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- A single row per (message, user). value is +1 (like) or -1 (dislike),
-- so a user can never like AND dislike the same message at once.
CREATE TABLE message_votes (
  message_id CHAR(36) NOT NULL,
  user_id    CHAR(36) NOT NULL,
  value      TINYINT  NOT NULL,
  PRIMARY KEY (message_id, user_id),
  KEY idx_votes_user (user_id),
  CONSTRAINT chk_votes_value CHECK (value IN (-1, 1)),
  CONSTRAINT fk_votes_message FOREIGN KEY (message_id)
    REFERENCES messages (id) ON DELETE CASCADE,
  CONSTRAINT fk_votes_user FOREIGN KEY (user_id)
    REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Friendship request: requester -> addressee. Accepted = friends both ways.
CREATE TABLE friendships (
  id           CHAR(36) NOT NULL,
  requester_id CHAR(36) NOT NULL,
  addressee_id CHAR(36) NOT NULL,
  status       ENUM('pending','accepted','declined') NOT NULL DEFAULT 'pending',
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_friendship_pair (requester_id, addressee_id),
  KEY idx_friendship_addressee (addressee_id),
  CONSTRAINT fk_friend_requester FOREIGN KEY (requester_id)
    REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_friend_addressee FOREIGN KEY (addressee_id)
    REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB;
