-- Forum backend — test data
-- Run AFTER schema.sql:  mysql -u root -p forum < db/seed.sql
--
-- Demo accounts (password):
--   admin  / Admin@123   (ADMIN)
--   alice  / Alice@123   (USER)
--   bob    / Bobby@123   (USER)

USE forum;

DELETE FROM friendships;
DELETE FROM message_votes;
DELETE FROM messages;
DELETE FROM topic_tags;
DELETE FROM tags;
DELETE FROM topics;
DELETE FROM users;

-- Users (salted SHA-512 hashes generated by src/utils/password.js)
INSERT INTO users (id, username, username_normalized, email, email_normalized, password_hash, password_salt, role, bio) VALUES
('5502edab-f011-452c-9933-9aa0877fbc36','admin','admin','admin@forum.dev','admin@forum.dev','5c616aa64e02d95fff2348c43f1c3b5c74830b6b0b57ae58d537e392ecc327fd93543d5d59f278e3b7066119a2b86b6f86f5a86ca9f0b6c57f00834c2b2ca593','9795bee3313ddd739169efaf3c9e03b6','ADMIN','Keeper of the signal.'),
('25af529b-4b1e-4f79-afc4-413cc9543a2d','alice','alice','alice@forum.dev','alice@forum.dev','f3006bc9cbd875bb692bc8d71e6560c6faeaa1228eaaa3e632332155957dac9f93fb1e8a4a0835be339e12e2272b54bfb2244d4369a4c7da6d4f6a40483f3570','b2ce67527394a25df17b5171daf887ae','USER','Front-end tinkerer.'),
('2621c5bb-6441-4e84-9a5a-a6f2ccac5cc8','bob','bob','bob@forum.dev','bob@forum.dev','8b37db2a889fa16452808312affbbedc2e20dbd765e68011371458a0697504f3b3a36adde3affa51a5b1a8f84e285fe903b6f193ec6b3d193055b821bd33d60c','57f14ba8581ef070ef4438396007cd88','USER','Backend gremlin.');

-- Tags
INSERT INTO tags (id, name) VALUES
('11111111-1111-1111-1111-111111111111','annonces'),
('22222222-2222-2222-2222-222222222222','javascript'),
('33333333-3333-3333-3333-333333333333','entraide'),
('44444444-4444-4444-4444-444444444444','design');

-- Topics
INSERT INTO topics (id, title, body, author_id, state, visibility, created_at) VALUES
('aaaaaaaa-0000-0000-0000-000000000001','Bienvenue sur le forum','Présentez-vous ici ! Ce topic restera ouvert.','5502edab-f011-452c-9933-9aa0877fbc36','open','public','2026-06-01 09:00:00'),
('aaaaaaaa-0000-0000-0000-000000000002','Comment hacher un mot de passe en SHA-512 ?','Je galère avec le module crypto de Node, un coup de main ?','25af529b-4b1e-4f79-afc4-413cc9543a2d','open','public','2026-06-05 14:30:00'),
('aaaaaaaa-0000-0000-0000-000000000003','Vieux thread archivé','Ancienne discussion, conservée pour archive.','2621c5bb-6441-4e84-9a5a-a6f2ccac5cc8','archived','public','2026-03-10 11:00:00');

INSERT INTO topic_tags (topic_id, tag_id) VALUES
('aaaaaaaa-0000-0000-0000-000000000001','11111111-1111-1111-1111-111111111111'),
('aaaaaaaa-0000-0000-0000-000000000002','22222222-2222-2222-2222-222222222222'),
('aaaaaaaa-0000-0000-0000-000000000002','33333333-3333-3333-3333-333333333333'),
('aaaaaaaa-0000-0000-0000-000000000003','33333333-3333-3333-3333-333333333333');

-- Messages
INSERT INTO messages (id, topic_id, author_id, body, created_at) VALUES
('bbbbbbbb-0000-0000-0000-000000000001','aaaaaaaa-0000-0000-0000-000000000001','25af529b-4b1e-4f79-afc4-413cc9543a2d','Salut tout le monde, ravie d''être là !','2026-06-01 10:15:00'),
('bbbbbbbb-0000-0000-0000-000000000002','aaaaaaaa-0000-0000-0000-000000000001','2621c5bb-6441-4e84-9a5a-a6f2ccac5cc8','Hello ! Premier message côté serveur.','2026-06-02 08:40:00'),
('bbbbbbbb-0000-0000-0000-000000000003','aaaaaaaa-0000-0000-0000-000000000002','2621c5bb-6441-4e84-9a5a-a6f2ccac5cc8','Regarde crypto.createHash(''sha512'') avec un sel par utilisateur.','2026-06-05 15:00:00');

-- Votes (+1 like / -1 dislike)
INSERT INTO message_votes (message_id, user_id, value) VALUES
('bbbbbbbb-0000-0000-0000-000000000003','25af529b-4b1e-4f79-afc4-413cc9543a2d',1),
('bbbbbbbb-0000-0000-0000-000000000003','5502edab-f011-452c-9933-9aa0877fbc36',1),
('bbbbbbbb-0000-0000-0000-000000000002','25af529b-4b1e-4f79-afc4-413cc9543a2d',-1);

-- Friendship (alice <-> bob accepted)
INSERT INTO friendships (id, requester_id, addressee_id, status) VALUES
('cccccccc-0000-0000-0000-000000000001','25af529b-4b1e-4f79-afc4-413cc9543a2d','2621c5bb-6441-4e84-9a5a-a6f2ccac5cc8','accepted');
